### ISSUE TITLE
Gradele Sync Issue: Error:Cause: dl.google.com:443 failed to respond

### ISSUE THREAD

**Issue by yongyanghz** [yongyanghz/Summary-Of-Android-Development-Issues-I-met#1]
Gradele Sync Issue: Error:Cause: dl.google.com:443 failed to respond
Fix: 
According to [the link](https://github.com/itgoyo/AndroidSummary/issues/59),  it's network proxy issue, just modify the file `~/.gradle/gradle.properties`, comment the https items.
```
systemProp.https.nonProxyHosts=localhost
 #systemProp.https.proxyPort=1080
 systemProp.http.proxyHost=127.0.0.1
 systemProp.http.nonProxyHosts=localhost
 #systemProp.https.proxyHost=127.0.0.1
 systemProp.http.proxyPort=1080
```

**Comment by zhaoweih** [comment]
Thanks!

**Comment by zhaoweih** [comment]
It works for me

**Comment by cristiansori2** [comment]
thanks it worked

**Comment by CNZp** [comment]
thanks it worked

**Comment by Wowgreat** [comment]
Does not work for me

**Comment by Babaktrad** [comment]
It works for me. But I don't understand why Android Studio notify me with the message `Sync is taking a significant amount of time to download dependencies.` and it really takes a long time to be finished.
Many thanks.

**Comment by Martins-pot** [comment]
thank you sooooooo much

**Comment by Martins-pot** [comment]
if it does not work for you, try this

1. make sure in your proxy settings. proxy is set to Auto detect
2. copy the files and paste them in your gradle.properties
3. sync gradle.

Note: Proxy should not be set to manual or no proxy. must be in auto detect
