### ISSUE TITLE
Ubuntu18.04 AVD: KVM is required to run this AVD. /dev/kvm device: permission denied.

### ISSUE THREAD

**Issue by yongyanghz** [yongyanghz/Summary-Of-Android-Development-Issues-I-met#11]
When running AVD in Android Studio on Ubuntu18.04
```
KVM is required to run this AVD.
/dev/kvm device: permission denied.

Grant current user access to /dev/kvm
```

**Comment by yongyanghz** [comment]
https://stackoverflow.com/questions/37300811/android-studio-dev-kvm-device-permission-denied
This is related to  that the user not authorized to use qemu-kvm.
### Step 1: check and install  the `qemu-kvm`,

`sudo apt install qemu-kvm`

### Step 2: check the ownership of  `/dev/kvm`

`ls -al /dev/kvm`

which shows 

`crw-rw---- 1 root kvm 10, 232 Jul 14 12:14 /dev/kvm`

means, it is owned by root now, and kvm groups can read write it.

### Step 3: add the user to kvm group

`sudo adduser [User_Name] kvm`

### Step 4
If still showing permission denied:

`sudo chown <Replace with username> /dev/kvm`

It works.

**Comment by mdaniyal9** [comment]
after 4th step it is still asking me to grant access
